"""add_expense_details_and_ai_fields

Revision ID: 1299bfeed0b1
Revises: 0e575431d384
Create Date: 2026-09-12 20:46:18.821283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1299bfeed0b1'
down_revision: Union[str, None] = '0e575431d384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.add_column('expenses', sa.Column('rejection_comment', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('ai_status', sa.String(length=50), nullable=False))
    op.add_column('expenses', sa.Column('ai_flag', sa.Boolean(), nullable=True))
    op.add_column('expenses', sa.Column('ai_flag_reason', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'ai_summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('expenses', 'approver_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('approver_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('expenses', 'ai_summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('expenses', 'decided_at')
    op.drop_column('expenses', 'ai_flag_reason')
    op.drop_column('expenses', 'ai_flag')
    op.drop_column('expenses', 'ai_status')
    op.drop_column('expenses', 'rejection_comment')
    op.drop_column('expenses', 'expense_date')
    # ### end Alembic commands ###
