"""init_db_and_ai_fields

Revision ID: f225df5864f4
Revises: b18b5a1efa40
Create Date: 2026-09-13 23:49:55.459714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f225df5864f4'
down_revision: Union[str, None] = 'b18b5a1efa40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
